feat: Added jsonpath documentation modal for jsonpath field in dynami…
UserOfficeProject/user-office-core pull request #235
Opened 2023-05-09 10:01 UTC by yoganandaness

## Description

Add a documentation modal for jsonpath field in dynamic multi-choice question and add the content to the modal

## Motivation and Context

The JSONPath field in Dynamic Multi choice question is quite a complex field, that needs a help option to understand what it is and how to use it efficiently. Hence, we are bringing in an Info tooltip as popup, which opens up a detailed documentation of the field.

## How Has This Been Tested

- Manually

## Changes

Introducing Popup using MUI Dialog. Worked only on a single file - apps/user-office-frontend/src/components/questionary/questionaryComponents/DynamicMultipleChoice/QuestionDynamicMultipleChoiceForm.tsx

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2023-05-09 11:13 UTC, yoganandaness commented
https://github.com/UserOfficeProject/user-office-core/assets/132274772/c6d1ae8f-a854-4140-87fc-2b7ba15636ba

2023-05-10 08:21 UTC, martin-trajanovski approved these changes
Great job! It seems that you are already up to speed with PR creation and following the commit guidelines. Just don't forget to update the title of the PR. It seems broken with the three dots at the end. 💯

2023-05-10 16:05 UTC, Junjiequan requested changes
on line 231 and line 232.  two inputProps were used can you remove one?
```
                inputProps={{ 'data-cy': 'dynamic-url-jsonPath' }}
                InputProps={{

```

2023-05-11 10:50 UTC, Junjiequan approved these changes

2023-05-11 10:51 UTC, merged