Fix stfc get users from fetching some users twice
UserOfficeProject/user-office-core pull request #303
Opened 2023-08-22 12:23 UTC by TCMeldrum

Small fix to stop the STFC data source from requesting users it already has found in the cache.

2023-08-23 09:50 UTC, RasmiaKulan approved these changes

2023-08-24 13:48 UTC, simonfernandes approved these changes
Nice catch 🕵️‍♂️

2023-08-24 13:53 UTC, ACLay requested changes

2023-08-24 13:53 UTC, ACLay commented on apps/user-office-backend/src/datasources/stfc/StfcUserDataSource.ts
> +      totalCount: userDetails.length,
It doesn't look like `finalTotalCount` is used now, can it be removed?

2023-08-24 14:17 UTC, ACLay approved these changes

2023-08-24 14:53 UTC, merged