Load pi information directly from calling component
UserOfficeProject/user-office-core pull request #314
Opened 2023-08-30 11:39 UTC by bolmsten

2023-08-30 17:04 UTC, enthusiastio commented on apps/user-office-frontend/src/components/questionary/questionaryComponents/ProposalBasis/QuestionaryComponentProposalBasis.tsx
> +      setPIData(userData);
There is a slight problem with it, because if you edit a proposal as User Officer it will set the PI as tie user officer

2023-08-31 08:00 UTC, martin-trajanovski requested changes

2023-08-31 08:00 UTC, martin-trajanovski commented on apps/user-office-frontend/src/components/questionary/questionaryComponents/ProposalBasis/QuestionaryComponentProposalBasis.tsx
> +  const { user } = useContext(UserContext);
If the logged in user is not used anymore I think it could be completely removed from here.

2023-08-31 09:34 UTC, martin-trajanovski approved these changes

2023-09-01 06:28 UTC, enthusiastio commented on apps/user-office-frontend/src/components/questionary/questionaryComponents/ProposalBasis/QuestionaryComponentProposalBasis.tsx
> +      setPIData(userData);
Works :+1:

2023-09-01 06:28 UTC, enthusiastio approved these changes

2023-09-01 08:16 UTC, simonfernandes approved these changes
Thanks for this @bolmsten

2023-09-01 12:46 UTC, merged