[WIP]feat: configure RabbitMQ status action
UserOfficeProject/user-office-core pull request #368
Opened 2023-09-29 14:02 UTC by martin-trajanovski

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2023-10-30 12:02 UTC, janosbabik requested changes
Hi Martin! Just some small changes that I think would be good to have.

2023-10-31 15:06 UTC, martin-trajanovski commented on apps/backend/src/datasources/postgres/ProposalDataSource.ts
> -    if (shouldResetStatusActions) {
This is removed so I think there is no need for transaction anymore I guess.

2023-11-01 09:42 UTC, janosbabik commented on apps/backend/src/datasources/postgres/ProposalDataSource.ts
> -    if (shouldResetStatusActions) {
It is recommended to use a transaction when there are multiple queries that depend on each other. We want these queries (like a single unit) to run simultaneously to ensure data consistency and efficient handling by the database. In this scenario, there is a possibility of data changing between the time we retrieve the "call" or "status_changing_events" and when we update the "proposal_events".

2023-11-03 11:09 UTC, janosbabik approved these changes

2023-11-03 14:36 UTC, Scott-James-Hurley commented
Is there a better way of exposing (or communicating) the ability to send a status action to a queue to a user? I don't think a User Officer should have to know what RabbitMQ is or what exchange is being used.

2023-11-03 14:55 UTC, Scott-James-Hurley commented
> Is there a better way of exposing (or communicating) the ability to send a status action to a queue to a user? I don't think a User Officer should have to know what RabbitMQ is or what an exchange is.
> 
> ![image](https://user-images.githubusercontent.com/44348929/280312347-a6d85c63-a24c-463c-85b9-ca7d2f587441.png)

Maybe the user should be just be told what the outcome will be of whatever consumes the event. This would be the description has to be configurable, maybe determined by the environment.

2023-11-07 08:41 UTC, Scott-James-Hurley approved these changes

2023-11-07 08:47 UTC, martin-trajanovski commented
> > Is there a better way of exposing (or communicating) the ability to send a status action to a queue to a user? I don't think a User Officer should have to know what RabbitMQ is or what an exchange is.
> > ![image](https://user-images.githubusercontent.com/44348929/280312347-a6d85c63-a24c-463c-85b9-ca7d2f587441.png)
> 
> Maybe the user should be just be told what the outcome will be of whatever consumes the event. This would be the description has to be configurable, maybe determined by the environment.

@Scott-James-Hurley I will open another ticket for this and we can discuss both within our team and on the planning meeting as well for improving the communication with the regular users so they can understand what this action outcome is and what to expect. Thanks for the feedback.

2023-11-07 09:21 UTC, merged