fix(db_patches): add missing technical reviews on proposals that are already assigned to an instrument
UserOfficeProject/user-office-core pull request #564
Opened 2024-03-25 14:55 UTC by martin-trajanovski

2024-03-26 09:57 UTC, yoganandaness requested changes

2024-03-26 09:57 UTC, yoganandaness commented on apps/backend/db_patches/0151_AddMissingTechnicalReviewsOnProposalsAssignedToInstrument.sql
> +    SELECT proposal_pk, ihs.instrument_id, i.manager_user_id reviewer_id, i.manager_user_id technical_review_assignee_id
`proposal_pk` does not have a prefix.

2024-04-03 12:37 UTC, yoganandaness approved these changes

2024-04-03 12:45 UTC, William-Edwards-STFC approved these changes

2024-04-04 05:55 UTC, merged