feat: add an option to have bcc recipient for emails sent through proposal status actions
UserOfficeProject/user-office-core pull request #667
Opened 2024-07-23 11:45 UTC by deepaksftc

## Description

Add an option to have bcc recipient for emails sent through proposal status actions.

## Motivation and Context

In STFC emails that we send, we need to include option to have bcc recipients.

## How Has This Been Tested

Manually

## Fixes

https://github.com/UserOfficeProject/issue-tracker/issues/1120

## Changes

apps/backend/src/eventHandlers/MailService/SMTPMailService.ts
apps/backend/src/models/Settings.ts
apps/backend/db_patches/0158_BccRecipientAppSetting.sql

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2024-07-25 13:19 UTC, janosbabik requested changes
It looks like a generic solution based on the BCC_EMAIL and the description; however, it is not. I am considering two options: the first is that BCC_EMAIL should be SMTP_BCC_EMAIL. In this case, we could say that this is a special setting which works in a specific case (SMTPMailService). The other solution could be to use the BCC in the SparkPost service as well. 

Additionally, the BCC will be used when CALL_CREATED or PROPOSAL_SUBMITTED events occur, not just when "proposal status actions" happen. Is this okay?

2024-07-25 13:26 UTC, deepaksftc commented
> It looks like a generic solution based on the BCC_EMAIL and the description; however, it is not. I am considering two options: the first is that BCC_EMAIL should be SMTP_BCC_EMAIL. In this case, we could say that this is a special setting which works in a specific case (SMTPMailService). The other solution could be to use the BCC in the SparkPost service as well.
> 
> Additionally, the BCC will be used when CALL_CREATED or PROPOSAL_SUBMITTED events occur, not just when "proposal status actions" happen. Is this okay?

Sure, I can change the name to SMTP_BCC_EMAIL. Yes, we need to add bcc for all set of mails. Gradually planning to move everything from handler to proposal status actions.

2024-07-25 13:27 UTC, deepaksftc commented on apps/backend/src/eventHandlers/MailService/SMTPMailService.spec.ts
> +    settingsValue: 'testmail@test.co',
sure, I will add it.

2024-07-29 10:17 UTC, janosbabik approved these changes

2024-07-30 10:19 UTC, ellen-wright approved these changes

2024-07-31 07:36 UTC, merged