feat: option to add technique picker question
UserOfficeProject/user-office-core pull request #688
Opened 2024-08-05 14:48 UTC by deepaksftc

## Description

This PR adds an option to have a technique picker question. 

## Motivation and Context

This is part of creating an STFC Xpress system in the software. You can see our plan so far and more discussion in https://github.com/UserOfficeProject/issue-tracker/discussions/1032#discussioncomment-9752530

## How Has This Been Tested

- General manual testing
- e2e tests
- Backend unit tests
- Manual graphql endpoint testing for schema validation

## Fixes

Fixes https://github.com/UserOfficeProject/issue-tracker/issues/1097

## Depends on

Validation: https://github.com/UserOfficeProject/user-office-lib/pull/201

## Tests included/Docs Updated?

-  I have added tests to cover my changes.
- [ ] All relevant doc has been updated

https://github.com/user-attachments/assets/86bb7ec3-bb65-4a7d-9dd3-b7643bbcef77

2024-08-14 08:27 UTC, simonfernandes commented on apps/e2e/cypress/e2e/techniques.cy.ts
> -    it('User officer should be able to assign and unassign instruments to technique without page refresh', function () {
No it doesn't, it was moved because the "advanced tests" have a more complex beforeEach set up to them, and this test doesn't require that.

2024-08-14 08:31 UTC, simonfernandes commented on apps/backend/src/mutations/TechniqueMutations.spec.ts
> +  });
Yes that's right, when the user answers the question we call the `assignProposalToTechniquesInternal` function instead

2024-08-14 09:19 UTC, ACLay approved these changes

2024-08-16 13:00 UTC, janosbabik requested changes
Hi @deepaksftc, nice job! I have a few suggestions to help resolve some issues.

2024-08-20 10:32 UTC, simonfernandes commented on apps/backend/src/mutations/TechniqueMutations.ts
> +  async assignProposalToTechnique(
We decided to keep a single mutation function for user officer access, which we will need to use in e2e tests in another PR, and we removed the "internal" wording from it to make it less confusing. The onBeforeSave function when answering the topic now calls the datasource directly as suggested, thanks.

2024-08-21 08:41 UTC, janosbabik requested changes
Thank you for your changes. One thing we need to address is removing the `technique_has_proposals` rows that were previously selected but are no longer selected. Is that correct?

2024-08-21 08:41 UTC, janosbabik commented on apps/backend/src/datasources/postgres/TechniqueDataSource.ts
> +    const checks = await Promise.all(
My suggestions are:
- If I’m correct, we need to remove the rows that are no longer selected
- You can use a single SQL query to check if a row exists before inserting:
```knex.raw('NSERT INTO … SELECT … WHERE NOT EXISTS ( SELECT 1 …```
- please use a transaction
If you need any help, please let me know

2024-08-23 07:53 UTC, janosbabik approved these changes

2024-08-23 08:12 UTC, merged