fix: add validation to files endpoints
UserOfficeProject/user-office-core pull request #714
Opened 2024-08-22 12:19 UTC by TCMeldrum

2024-08-23 07:05 UTC, janosbabik requested changes
Thanks @TCMeldrum , for fixing this issue! Just one suggestion from me.

2024-08-23 09:12 UTC, janosbabik approved these changes

2024-08-23 09:20 UTC, ellen-wright approved these changes

2024-08-23 12:41 UTC, merged

2024-09-02 08:32 UTC, gnyiri commented
We tested upload/download at ELI and found that the validation prevents downloading files (401 error).

2024-09-02 11:19 UTC, TCMeldrum commented
Yeah sorry forgot to add the request header to the download links thought that kind of thing would have been picked up by the tests, working on a fix now.