Preview for all templates
UserOfficeProject/user-office-core pull request #723
Opened 2024-08-26 09:47 UTC by bolmsten

2024-08-27 07:18 UTC, janosbabik requested changes

2024-08-27 07:18 UTC, janosbabik commented on apps/frontend/src/components/template/PreviewTemplateModal.tsx
> +  console.log(templateId, questionarySteps, templateGroupId);
```suggestion
```

2024-09-10 11:57 UTC, janosbabik approved these changes

2024-09-13 13:14 UTC, TCMeldrum approved these changes

2024-10-01 10:26 UTC, merged