feat: add tech review comment and reviewer names to stfc fap export
UserOfficeProject/user-office-core pull request #763
Opened 2024-09-12 15:58 UTC by TCMeldrum

2024-09-20 10:33 UTC, Scott-James-Hurley requested changes

2024-09-26 09:34 UTC, Scott-James-Hurley commented on apps/e2e/cypress/e2e/FAPs.cy.ts
> +  it('Officer should be able to download of all FAP meetings in excel stfc', function () {
```suggestion
  it('Officer should be able to download all FAP meetings in excel stfc', function () {
```

I missed a spot

2024-09-27 10:43 UTC, Scott-James-Hurley approved these changes

2024-09-30 10:01 UTC, TCMeldrum commented
@janosbabik could you have a look at this please? Thanks!

2024-10-02 11:31 UTC, yoganandaness approved these changes

2024-10-03 13:49 UTC, merged