update: preparations to change ELI terminology on UI
UserOfficeProject/user-office-core pull request #774
Opened 2024-09-17 08:57 UTC by gnyiri

## Description

Add t macros to UI strings we would like to rename at ELI. 

## Motivation and Context

Change UI terminology for ELI.

## How Has This Been Tested

Manual tests + auto tests. 

## Fixes

N/A

## Changes

Add t macros to some strings in frontend code.

## Depends on

N/A

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2024-09-17 16:03 UTC, TCMeldrum requested changes
Can you add "Fap" to https://github.com/UserOfficeProject/user-office-core/blob/develop/apps/frontend/public/locales/override/translation.json

2024-09-18 12:59 UTC, gnyiri commented
> Can you add "Fap" to https://github.com/UserOfficeProject/user-office-core/blob/develop/apps/frontend/public/locales/override/translation.json thanks!

I added all necessary keys, thanks.

2024-09-18 13:47 UTC, TCMeldrum approved these changes

2024-09-20 11:06 UTC, janosbabik approved these changes

2024-09-20 12:34 UTC, merged