fix: dont show expired proposals in exports
UserOfficeProject/user-office-core pull request #805
Opened 2024-10-04 09:55 UTC by TCMeldrum

Closes UserOfficeProject/issue-tracker#1093

## Description
This PR ensures that expired proposals are not shown in exports.

## Motivation and Context
The change was required to avoid confusion and maintain accuracy in the exported data by excluding proposals that are expired or in draft status.

## Changes
1. A condition has been added in `0163_ExcludeExpiredProposalsFromReviewProposalView.sql` to filter out expired and draft proposals from the 'review_data' view.
2. A new test case has been added in `FAPs.cy.ts` to verify that expired proposals do not appear in exports.
3. A new fixture file `exampleFapExportExpired.json` has been created to help in the testing process.

## How Has This Been Tested?

## Fixes Jira Issue

[https://jira.esss.lu.se/browse/](https://jira.esss.lu.se/browse/)

## Depends On

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2024-10-08 10:58 UTC, yoganandaness requested changes

2024-10-08 10:58 UTC, yoganandaness commented on apps/e2e/cypress/e2e/FAPs.cy.ts
> +  it.only('Expired proposals should not appear in exports', function () {
```suggestion
  it('Expired proposals should not appear in exports', function () {
```

2024-10-08 11:11 UTC, yoganandaness approved these changes

2024-10-10 10:48 UTC, Scott-James-Hurley approved these changes

2024-10-11 20:49 UTC, merged