feat: allow fap chairs and secs to update tech reviews
UserOfficeProject/user-office-core pull request #807
Opened 2024-10-07 13:48 UTC by TCMeldrum

2024-10-08 10:56 UTC, yoganandaness requested changes

2024-10-08 10:56 UTC, yoganandaness commented on apps/backend/db_patches/0164_AllowSecsEditTechReview.sql
> +        VALUES ('SECS_EDIT_TECH_REVIEWS',
```suggestion
        VALUES ('FAP_SECS_EDIT_TECH_REVIEWS', 
```

2024-10-08 11:12 UTC, yoganandaness approved these changes

2024-10-10 10:08 UTC, Scott-James-Hurley approved these changes
I can't see a situation where this arises but if the status or time allocation fields are empty then the secretary can't save their comments.

2024-10-14 09:44 UTC, merged