feat: serverside pagination for the questions table done
UserOfficeProject/user-office-core pull request #836
Opened 2024-10-30 11:39 UTC by yoganandaness

## Description

Serverside Pagination for the questions table

## Motivation and Context

Improve performance in the questions table

## How Has This Been Tested

Manually. Test cases also have been updated. Extensive test case for server side pagination need to be done in a separate task. 

## Fixes

## Changes

Backend query change to facilitate serverside pagination. 

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2024-11-14 14:17 UTC, Scott-James-Hurley requested changes
This looks great. I did notice though that when trying to sort by number of answers or number of templates an error is thrown. It looks like the value passed as `sortField` is either `answerCountButton` or `templateCountButton`, neither of which are in `fieldMap`. Could this please be addressed? I understand the reasoning behind putting paginated table tests in a different PR but perhaps this should wait until the tests are ready? Would like to hear people's thoughts.

2024-11-25 13:03 UTC, yoganandaness commented
> This looks great. I did notice though that when trying to sort by number of answers or number of templates an error is thrown. It looks like the value passed as `sortField` is either `answerCountButton` or `templateCountButton`, neither of which are in `fieldMap`. Could this please be addressed? I understand the reasoning behind putting paginated table tests in a different PR but perhaps this should wait until the tests are ready? Would like to hear people's thoughts.

Thanks for the comment @Scott-James-Hurley. I have fixed the issue with sorting the column of Answers count and Templates count. Also, as you mentioned, it is a good idea to wait for the test cases before merging the PR. I am expecting to write the test cases for these next week. Will club these together. 

Until then, moving this to Draft.

2024-12-19 11:35 UTC, jekabs-karklins reviewed
@yoganandaness I really like the PR, especially the frontend part 👍🏻 
I just left a comment one for the backed but looks good so I can already approve it.

2024-12-19 11:35 UTC, jekabs-karklins commented on apps/backend/src/resolvers/queries/QuestionsQuery.ts
> +  public excludeDataType?: DataType[];
question: It appears that the excludeDataType is not used? Shall we remove it then?

2024-12-19 11:39 UTC, jekabs-karklins commented
> @yoganandaness I really like the PR, especially the frontend part 👍🏻 I just left a comment one for the backed but looks good so I can already approve it, or is this still in draft?

@yoganandaness 
Ah, I just noticed the reason for it being in the draft. Okay, I'll wait 👍🏻

2024-12-20 21:24 UTC, jekabs-karklins approved these changes

2025-01-03 10:34 UTC, Scott-James-Hurley commented
When accessing the questions table I get the following error:
`Variable "$filter" got invalid value { excludeDataType: ["FEEDBACK_BASIS", "GENERIC_TEMPLATE_BASIS", "PROPOSAL_BASIS", "PROPOSAL_ESI_BASIS", "SAMPLE_BASIS", "SAMPLE_ESI_BASIS", "SHIPMENT_BASIS", "VISIT_BASIS", "FAP_REVIEW_BASIS"] }; Field "excludeDataType" is not defined by type "AllQuestionsFilter". Did you mean "dataType"?`
Perhaps I missed something when running it locally?

2025-01-09 14:23 UTC, yoganandaness commented
> When accessing the questions table I get the following error: `Variable "$filter" got invalid value { excludeDataType: ["FEEDBACK_BASIS", "GENERIC_TEMPLATE_BASIS", "PROPOSAL_BASIS", "PROPOSAL_ESI_BASIS", "SAMPLE_BASIS", "SAMPLE_ESI_BASIS", "SHIPMENT_BASIS", "VISIT_BASIS", "FAP_REVIEW_BASIS"] }; Field "excludeDataType" is not defined by type "AllQuestionsFilter". Did you mean "dataType"?` Perhaps I missed something when running it locally?

Thank for bringing this. Yes, i missed adding the excludeDatatype filter in the query. It has been added in the backend and working fine now.

2025-01-10 09:28 UTC, Scott-James-Hurley approved these changes
Thanks!

2025-01-14 08:52 UTC, jekabs-karklins approved these changes
Looks good

2025-01-14 13:50 UTC, merged